//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenChurchManagementSystem.WebApi.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IChurchService : SkyWeb.DatVM.Data.IBaseService<Church>
    {
    }
    
    public partial class ChurchService : SkyWeb.DatVM.Data.BaseService<Church>, IChurchService
    {
        public ChurchService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IChurchRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
