//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenChurchManagementSystem.WebApi.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IIdentityAccountService : SkyWeb.DatVM.Data.IBaseService<IdentityAccount>
    {
    }
    
    public partial class IdentityAccountService : SkyWeb.DatVM.Data.BaseService<IdentityAccount>, IIdentityAccountService
    {
        public IdentityAccountService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IIdentityAccountRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
