//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenChurchManagementSystem.WebApi.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IIdentityRoleService : SkyWeb.DatVM.Data.IBaseService<IdentityRole>
    {
    }
    
    public partial class IdentityRoleService : SkyWeb.DatVM.Data.BaseService<IdentityRole>, IIdentityRoleService
    {
        public IdentityRoleService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IIdentityRoleRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
