//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenChurchManagementSystem.WebApi.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IIdentityClaimService : SkyWeb.DatVM.Data.IBaseService<IdentityClaim>
    {
    }
    
    public partial class IdentityClaimService : SkyWeb.DatVM.Data.BaseService<IdentityClaim>, IIdentityClaimService
    {
        public IdentityClaimService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IIdentityClaimRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
