//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenChurchManagementSystem.WebApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityAccountRole
    {
        public int Id { get; set; }
        public int IdentityAccountId { get; set; }
        public string IdentityRoleId { get; set; }
        public bool Active { get; set; }
    
        public virtual IdentityAccount IdentityAccount { get; set; }
        public virtual IdentityRole IdentityRole { get; set; }
    }
}
