//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenChurchManagementSystem.WebApi.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IIdentityClaimRepository : SkyWeb.DatVM.Data.IBaseRepository<IdentityClaim>
    {
    }
    
    public partial class IdentityClaimRepository : SkyWeb.DatVM.Data.BaseRepository<IdentityClaim>, IIdentityClaimRepository
    {
    	public IdentityClaimRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
        {
        }
    }
}
