//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenChurchManagementSystem.WebApi.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IIdentityAccountRepository : SkyWeb.DatVM.Data.IBaseRepository<IdentityAccount>
    {
    }
    
    public partial class IdentityAccountRepository : SkyWeb.DatVM.Data.BaseRepository<IdentityAccount>, IIdentityAccountRepository
    {
    	public IdentityAccountRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
        {
        }
    }
}
