//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenChurchManagementSystem.WebApi.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IIdentityRoleRepository : SkyWeb.DatVM.Data.IBaseRepository<IdentityRole>
    {
    }
    
    public partial class IdentityRoleRepository : SkyWeb.DatVM.Data.BaseRepository<IdentityRole>, IIdentityRoleRepository
    {
    	public IdentityRoleRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
        {
        }
    }
}
