//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenChurchManagementSystem.WebApi.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityAccountViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<OpenChurchManagementSystem.WebApi.Models.Entities.IdentityAccount>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int ChurchId { get; set; }
    			public virtual string UserName { get; set; }
    			public virtual string Email { get; set; }
    			public virtual string PasswordHash { get; set; }
    			public virtual string SecurityStamp { get; set; }
    			public virtual string AdminNote { get; set; }
    			public virtual string SysAdminNote { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public IdentityAccountViewModel() : base() { }
    	public IdentityAccountViewModel(OpenChurchManagementSystem.WebApi.Models.Entities.IdentityAccount entity) : base(entity) { }
    
    }
}
