//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenChurchManagementSystem.WebApi.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityClaimViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<OpenChurchManagementSystem.WebApi.Models.Entities.IdentityClaim>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int UserId { get; set; }
    			public virtual string ClaimType { get; set; }
    			public virtual string ClaimValue { get; set; }
    	
    	public IdentityClaimViewModel() : base() { }
    	public IdentityClaimViewModel(OpenChurchManagementSystem.WebApi.Models.Entities.IdentityClaim entity) : base(entity) { }
    
    }
}
