//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenChurchManagementSystem.WebApi.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityAccountRoleViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<OpenChurchManagementSystem.WebApi.Models.Entities.IdentityAccountRole>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int IdentityAccountId { get; set; }
    			public virtual string IdentityRoleId { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public IdentityAccountRoleViewModel() : base() { }
    	public IdentityAccountRoleViewModel(OpenChurchManagementSystem.WebApi.Models.Entities.IdentityAccountRole entity) : base(entity) { }
    
    }
}
